services:

  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
    networks:
      - devops-network

  redis:
    image: redis:7-alpine
    container_name: devops-redis
    ports:
      - "6379:6379"
    logging:
      driver: loki
      options:
        loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
        loki-retries: "5"
    networks:
      - devops-network

  prometheus:
    image: prom/prometheus
    container_name: devops-prometheus
    network_mode: host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: devops-grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:3.7.0
    container_name: devops-loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

networks:
  devops-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: