services:

  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - devops-network

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - devops-network

  redis:
    image: redis:7-alpine
    container_name: devops-redis
    ports:
      - "6379:6379"
    networks:
      - devops-network

  prometheus:
    image: prom/prometheus
    container_name: devops-prometheus
    network_mode: host
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: devops-grafana
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

networks:
  devops-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: